[build]
  functions = "netlify/functions"

# Configuración de cache para imágenes
[[headers]]
  for = "/.netlify/functions/image-proxy/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    CDN-Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200